spring:
  application:
    name: user-mgmt-service
  datasource:
    url: ${PG_DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${PG_USERNAME:user_manager}
    password: ${PG_PASSWORD:password}
    hikari:
      jdbc-url: ${PG_DB_URL:jdbc:postgresql://localhost:5432/user_db}
      maximum-pool-size: 10
      pool-name: USER-DB-CONN-POOL


  mvc:
    apiversion:
      use:
        header: "Api-Version"
  threads:
    virtual:
      enabled: false
  jpa:
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BS_SERVERS:localhost:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
server:
  port: 8081
