spring:
  application:
    name: user-mgmt-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user_manager
    password: password
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/user_db
      maximum-pool-size: 100
      pool-name: USER-DB-CONN-POOL
  mvc:
    apiversion:
      use:
        header: "Api-Version"
  threads:
    virtual:
      enabled: false

