spring:
  application:
    name: wallet-service

  datasource:
    url: ${PG_DB_URL:jdbc:postgresql://localhost:5432/wallet_db}
    username: ${PG_USERNAME:wallet_manager}
    password: ${PG_PASSWORD:password}
    hikari:
      jdbc-url: ${PG_DB_URL:jdbc:postgresql://localhost:5432/wallet_db}
      maximum-pool-size: 10
      pool-name: WALLET-DB-CONN-POOL

  threads:
    virtual:
      enabled: false
  jpa:
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BS_SERVERS:localhost:9094}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer